name: Publish new boilerplate version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code to runner
        uses: actions/checkout@v2

      - name: Create .tar.gz files for each folder
        run: |
          find * -maxdepth 0 -type d -exec tar czvf {}.tar.gz {} \;
          mkdir -p tars
          mv *.tar.gz tars/

      - run: ls -a tars

      - name: Upload compiled files
        uses: actions/upload-artifact@v2
        with:
          name: tar-files
          path: tars/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download compiled files
        uses: actions/download-artifact@v2
        with:
          name: tar-files

      - name: View content
        run: ls -R
      
      - name: Create a new GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}.0
          release_name: Boilerplates v${{ github.run_number }}.0

      - name: Upload files to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: v${{ github.run_number }}.0
